spring:
  application:
    name: dbcrypt
  main:
    lazy-initialization: false
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${io.github.paulushcgcj.database.host}/${io.github.paulushcgcj.database.name}?ssl=true&sslmode=require&options=-c%20cryptic.key=${io.github.paulushcgcj.database.key}
    username: ${io.github.paulushcgcj.database.username}
    password: ${io.github.paulushcgcj.database.password}
    ssl: true
    ssl-root-cert: ${io.github.paulushcgcj.database.ssl-path}
    hikari:
      connectionTimeout: 90000
      idleTimeout: 45000
      maxLifetime: 60000
      keepaliveTime: 30000
      poolName: DbCryptPool
      minimumIdle: 1
      maximumPoolSize: 3
  flyway:
    validate-on-migrate: true
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
io:
  github:
    paulushcgcj:
      database:
        host: ${DB_HOST:localhost}
        name: ${DB_NAME:dbcrypt}
        username: ${DB_USER:default}
        password: ${DB_PASS:default}
        key: ${DB_KEY:AES_KEY}
        ssl-path: ${SSL_PATH}
