spring:
  application:
    name: dbcrypt
  main:
    lazy-initialization: false
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${io.github.paulushcgcj.database.host}/${io.github.paulushcgcj.database.name}
    username: ${io.github.paulushcgcj.database.username}
    password: ${io.github.paulushcgcj.database.password}
    hikari:
      connectionTimeout: 90000
      idleTimeout: 45000
      maxLifetime: 60000
      keepaliveTime: 30000
      poolName: DbCryptPool
      minimumIdle: 1
      maximumPoolSize: 3

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

io:
  github:
    paulushcgcj:
      database:
        host: ${DB_HOST:localhost}
        name: ${DB_NAME:dbcrypt}
        username: ${DB_USER:default}
        password: ${DB_PASS:default}