spring:
  application:
    name: dbcrypt-mono
  main:
    lazy-initialization: false
    banner-mode: "off"
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://${io.github.paulushcgcj.database.host}/${io.github.paulushcgcj.database.name}?options=cryptic.key=${io.github.paulushcgcj.database.key}
    username: ${io.github.paulushcgcj.database.username}
    password: ${io.github.paulushcgcj.database.password}
    pool:
      enabled: true
      initialSize: 1
      minIdle: 1
      maxSize: 3
      maxLifeTime: 60000
      maxIdleTime: 45000
      maxCreateConnectionTime: 90000
      poolName: DbCryptReactivePool
  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    user: ${io.github.paulushcgcj.database.username}
    password: ${io.github.paulushcgcj.database.password}
    url: jdbc:postgresql://${io.github.paulushcgcj.database.host}/${io.github.paulushcgcj.database.name}?options=-c%20cryptic.key=${io.github.paulushcgcj.database.key}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info


io:
  github:
    paulushcgcj:
      database:
        host: ${DB_HOST:localhost}
        name: ${DB_NAME:dbcrypt}
        username: ${DB_USER:default}
        password: ${DB_PASS:default}
        key: ${DB_KEY:AES_KEY}